// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GuHCH-Js1LPEgaRZ8MD4JZ-HkMLE9LU',
    appId: '1:265371327357:web:0bd35f424edcfb8a4fca14',
    messagingSenderId: '265371327357',
    projectId: 'medical-pharmacy-4efe4',
    authDomain: 'medical-pharmacy-4efe4.firebaseapp.com',
    storageBucket: 'medical-pharmacy-4efe4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEkcmzHCkKOIs3ersmuOsp4gWonsg173M',
    appId: '1:265371327357:android:d40f5e047b910bd04fca14',
    messagingSenderId: '265371327357',
    projectId: 'medical-pharmacy-4efe4',
    storageBucket: 'medical-pharmacy-4efe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9db2zLNTM5nTpPwANYCofu7cLSvwff1o',
    appId: '1:265371327357:ios:8827513490d1ea6a4fca14',
    messagingSenderId: '265371327357',
    projectId: 'medical-pharmacy-4efe4',
    storageBucket: 'medical-pharmacy-4efe4.firebasestorage.app',
    iosBundleId: 'com.example.medicalPharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9db2zLNTM5nTpPwANYCofu7cLSvwff1o',
    appId: '1:265371327357:ios:8827513490d1ea6a4fca14',
    messagingSenderId: '265371327357',
    projectId: 'medical-pharmacy-4efe4',
    storageBucket: 'medical-pharmacy-4efe4.firebasestorage.app',
    iosBundleId: 'com.example.medicalPharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7GuHCH-Js1LPEgaRZ8MD4JZ-HkMLE9LU',
    appId: '1:265371327357:web:1250db2379875fae4fca14',
    messagingSenderId: '265371327357',
    projectId: 'medical-pharmacy-4efe4',
    authDomain: 'medical-pharmacy-4efe4.firebaseapp.com',
    storageBucket: 'medical-pharmacy-4efe4.firebasestorage.app',
  );
}
